### ISSUE TITLE
好想看您在Gitbook分享的Cobalt Strike教程啊

### ISSUE THREAD

**Issue by CatAndCoffee** [WBGlIl/WBGlIl.github.io#1]
这两天在看您在Gitbook上分享的Cobalt Strike的教程，但是今天突然发现设置为了私有，是不继续公开了吗？

**Comment by WBGlIl** [comment]
旧版gitbook挂了没办法继续更新了只能移动到新版gitbookhttps://wbglil.gitbook.io/cobalt-strike/
